### ISSUE TITLE
bug: Failed to run start script

### ISSUE THREAD

**Issue by liebkne** [second-state/LlamaEdge#100] opened 2024-01-31 05:07 UTC
### Summary

`bash <(curl -sSfL 'https://code.flows.network/webhook/iwYN1SdN3AmPgR5ao5Gt/run-llm.sh')`

error:

`sed: /Users/user/.bash_profile: in-place editing only works for regular files`

### Reproduction steps

1. Run `bash <(curl -sSfL 'https://code.flows.network/webhook/iwYN1SdN3AmPgR5ao5Gt/run-llm.sh')`
2. Press `Enter`
3. Press `1`
4. Press `Enter`

### Screenshots

<img width="655" alt="Screenshot 2024-01-31 at 13 05 42" src="https://github.com/second-state/LlamaEdge/assets/5475262/d4be4325-f0a5-4c89-9d45-d96bb7e26bba">

### Model Information

None

### Operating system information

macOS 14.2.1 (23C71)

### ARCH

Not sure

### CPU Information

2.6 GHz 6-Core Intel Core i7

### Memory Size

32GB

### GPU Information

Radeon Pro 560X 4 GB Intel UHD Graphics 630 1536 MB

### VRAM Size

Not sure

**Comment by hydai** [comment] 2024-01-31 05:57
Hi @liebkne 
May I ask what the state of `.bash_profile` is? Is it a symbolically linked file?

**Comment by liebkne** [comment] 2024-01-31 05:58
Hello, yes, it is.

**Comment by hydai** [comment] 2024-01-31 06:02
Could you please remove the wasmedge-related section inside your `.bash_profile` as a workaround?
I already raised an issue on WasmEdge about the uninstaller issue.

**Comment by liebkne** [comment] 2024-01-31 06:09
I tried and another issue happened 

```
[I] This is a helper script for deploying LlamaEdge API Server on this machine.

    The following tasks will be done:
    - Download GGUF model
    - Install WasmEdge Runtime and the wasi-nn_ggml plugin
    - Download LlamaEdge API Server

    Upon the tasks done, an HTTP server will be started and it will serve the selected
    model.

    Please note:

    - All downloaded files will be stored in the current folder
    - The server will be listening on all network interfaces
    - The server will run with default settings which are not always optimal
    - Do not judge the quality of a model based on the results from this script
    - This script is only for demonstration purposes

    During the whole process, you can press Ctrl-C to abort the current process at any time.

    Press Enter to continue ...


[+] Installing WasmEdge ...

No root permissions.
Installation path found at /Users/user/.wasmedge
Removing /Users/user/.wasmedge/bin
Removing /Users/user/.wasmedge/bin/wasmedge
Removing /Users/user/.wasmedge/bin/wasmedgec
Removing /Users/user/.wasmedge/include
Removing /Users/user/.wasmedge/include/wasmedge/wasmedge.h
Removing /Users/user/.wasmedge/include/wasmedge/version.h
Removing /Users/user/.wasmedge/include/wasmedge/enum.inc
Removing /Users/user/.wasmedge/include/wasmedge/enum_configure.h
Removing /Users/user/.wasmedge/include/wasmedge/enum_errcode.h
Removing /Users/user/.wasmedge/include/wasmedge/int128.h
Removing /Users/user/.wasmedge/include/wasmedge/enum_types.h
Removing /Users/user/.wasmedge/lib
Removing /Users/user/.wasmedge/lib/libwasmedge.0.dylib
Removing /Users/user/.wasmedge/lib/libwasmedge.0.0.3.tbd
Removing /Users/user/.wasmedge/lib/libwasmedge.tbd
Removing /Users/user/.wasmedge/lib/libwasmedge.dylib
Removing /Users/user/.wasmedge/lib/libwasmedge.0.0.3.dylib
Removing /Users/user/.wasmedge/lib/libwasmedge.0.tbd
Removing /Users/user/.wasmedge/plugin/libwasmedgePluginWasiNN.dylib
Removing /Users/user/.wasmedge/env
Removing /Users/user/.wasmedge/bin
Removing /Users/user/.wasmedge/include/wasmedge
Removing /Users/user/.wasmedge/plugin
Removing /Users/user/.wasmedge/lib
Removing /Users/user/.wasmedge/include
Removing /Users/user/.wasmedge
Using Python: /Users/user/Downloads/demo/.direnv/python-3.10/bin/python3 
INFO    - CUDA is only supported on Linux
INFO    - CUDA is only supported on Linux
WARNING - Experimental Option Selected: plugins
WARNING - plugins option may change later
INFO    - Compatible with current configuration
INFO    - Running Uninstaller
WARNING - Uninstaller did not find previous installation
WARNING - SHELL variable not found. Using bash as SHELL
INFO    - shell configuration updated
INFO    - Downloading WasmEdge
|============================================================|100.00 %INFO    - Downloaded
INFO    - Installing WasmEdge
INFO    - WasmEdge Successfully installed
INFO    - Downloading Plugin: wasi_nn-ggml
|============================================================|100.00 %INFO    - Downloaded
INFO    - Run:
source /Users/user/.bash_profile

    The WasmEdge Runtime is installed in /Users/user/.wasmedge/bin/wasmedge.

    * To uninstall it, use the command 'bash <(curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/uninstall.sh) -q'

[+] The most popular models at https://huggingface.co/second-state:

     1) Llama-2-7B-Chat-GGUF
     2) stablelm-2-zephyr-1.6b-GGUF
     3) OpenChat-3.5-0106-GGUF
     4) Yi-34B-Chat-GGUF
     5) Yi-34Bx2-MoE-60B-GGUF
     6) Deepseek-LLM-7B-Chat-GGUF
     7) Deepseek-Coder-6.7B-Instruct-GGUF
     8) Mistral-7B-Instruct-v0.2-GGUF
     9) dolphin-2.6-mistral-7B-GGUF
    10) Orca-2-13B-GGUF
    11) TinyLlama-1.1B-Chat-v1.0-GGUF
    12) SOLAR-10.7B-Instruct-v1.0-GGUF

    Or choose one from: https://huggingface.co/models?sort=trending&search=gguf

[+] Please select a number from the list above or enter an URL: 11
[+] Downloading the selected model from https://huggingface.co/second-state/TinyLlama-1.1B-Chat-v1.0-GGUF/resolve/main/TinyLlama-1.1B-Chat-v1.0-Q5_K_M.gguf
################################################################################################################################## 100.0%################################################################################################################################## 100.0%
[+] Extracting prompt type: chatml 
[+] No reverse prompt required
[+] Running mode: 

     1) API Server with Chatbot web app
     2) CLI Chat

[+] Select a number from the list above: 2
[+] Selected running mode: 2 (CLI Chat)
[+] The latest three releases of LlamaEdge CLI Chatbot: 

     1)   LlamaEdge 0.2.9
     2)   LlamaEdge 0.2.8
     3)   LlamaEdge 0.2.7

[+] Select a number from the list above: 1
[+] Downloading llama-chat.wasm to the current directory

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2572k  100 2572k    0     0  1003k      0  0:00:02  0:00:02 --:--:-- 4834k
[+] Will run the following command to start CLI Chat:

    wasmedge --dir .:. --nn-preload default:GGML:AUTO:TinyLlama-1.1B-Chat-v1.0-Q5_K_M.gguf llama-chat.wasm --prompt-template chatml

[+] Confirm to start CLI Chat? (y/n): y

********************* LlamaEdge *********************

[INFO] Model alias: default
[INFO] Prompt context size: 512
[INFO] Number of tokens to predict: 1024
[INFO] Number of layers to run on the GPU: 100
[INFO] Batch size for prompt processing: 512
[INFO] Temperature for sampling: 0.8
[INFO] Penalize repeat sequence of tokens: 1.1
[INFO] Use default system prompt
[INFO] Prompt template: ChatML
[INFO] Log prompts: false
[INFO] Log statistics: false
[INFO] Log all information: false
thread 'main' panicked at src/main.rs:332:49:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2024-01-31 14:08:13.014] [error] execution failed: unreachable, Code: 0x89
[2024-01-31 14:08:13.014] [error]     In instruction: unreachable (0x00) , Bytecode offset: 0x0006dae8
[2024-01-31 14:08:13.014] [error]     When executing function name: "_start"
```

**Comment by hydai** [comment] 2024-01-31 06:26
@liebkne 
I don't have an Intel model macbook with me now. I will use GitHub CI Runner to reproduce this issue. Will get you back once I have the result. Thanks!

**Comment by hydai** [comment] 2024-01-31 18:39
Hi @liebkne 
The `execution failed: unreachable, Code: 0x89` is caused by the wrong version of the plugin. I already uploaded the correct one. Could you please try again? It should download the right version now.

**Comment by hydai** [comment] 2024-01-31 18:43
And I found that your GPU memory is a little bit small for running some LLM models. If you are trying to execute a larger model, you may need to append `--n-gpu-layers <a small value>` after the execution command, and run the command by youself:

```bash
[+] Will run the following command to start CLI Chat:

        wasmedge --dir .:. --nn-preload default:GGML:AUTO:Llama-2-7b-chat-hf-Q5_K_M.gguf llama-chat.wasm --prompt-template llama-2-chat --n-gpu-layers <a smaller value>
```

**Comment by liebkne** [comment] 2024-02-01 02:32
@hydai Hello, I start from a fresh state (removing related things from `.bash_profile`) and now get the bellow error

```
user@macos:~/Downloads $ bash <(curl -sSfL 'https://code.flows.network/webhook/iwYN1SdN3AmPgR5ao5Gt/run-llm.sh')

[I] This is a helper script for deploying LlamaEdge API Server on this machine.

    The following tasks will be done:
    - Download GGUF model
    - Install WasmEdge Runtime and the wasi-nn_ggml plugin
    - Download LlamaEdge API Server

    Upon the tasks done, an HTTP server will be started and it will serve the selected
    model.

    Please note:

    - All downloaded files will be stored in the current folder
    - The server will be listening on all network interfaces
    - The server will run with default settings which are not always optimal
    - Do not judge the quality of a model based on the results from this script
    - This script is only for demonstration purposes

    During the whole process, you can press Ctrl-C to abort the current process at any time.

    Press Enter to continue ...


[+] Installing WasmEdge ...

No root permissions.
Cannot detect installation path
Failed to uninstall WasmEdge
user@macos:~/Downloads $ 
```

and thanks for the tip!

**Comment by hydai** [comment] 2024-02-01 02:36
Hi @liebkne 
We are aware of this bug, it will be fixed in #101 
Ref: https://github.com/second-state/LlamaEdge/pull/101/files#diff-10358b022767068e6ae38cf2a180b04cf4524e14b66c5604369c5243aa661856L191

**Comment by liebkne** [comment] 2024-02-01 02:38
So how should I rerun the start script?

**Comment by hydai** [comment] 2024-02-01 02:48
> So how should I rerun the start script?

The PR has just been merged; please try it again directly.

**Comment by hydai** [comment] 2024-02-01 03:38
> And I found that your GPU memory is a little bit small for running some LLM models. If you are trying to execute a larger model, you may need to append `--n-gpu-layers <a small value>` after the execution command, and run the command by youself:
> 
> ```shell
> [+] Will run the following command to start CLI Chat:
> 
>         wasmedge --dir .:. --nn-preload default:GGML:AUTO:Llama-2-7b-chat-hf-Q5_K_M.gguf llama-chat.wasm --prompt-template llama-2-chat --n-gpu-layers <a smaller value>
> ```

Could you please append `--n-gpu-layers 0` to the options list to disable GPU? I have tested it on a MacBook i9 + Radeon Pro 5600M GPU. However, it looks like the Intel model + different GPU is not fully supported by the upstream. We are going to disable the AMD GPU support by default in the next update.

**Comment by liebkne** [comment] 2024-02-01 03:42
Ah, seems to work now, thanks!

```
user@macos:~/Downloads $ wasmedge --dir .:. --nn-preload default:GGML:AUTO:TinyLlama-1.1B-Chat-v1.0-Q5_K_M.gguf llama-chat.wasm --prompt-template chatml --n-gpu-layers 0
[INFO] Model alias: default
[INFO] Prompt context size: 512
[INFO] Number of tokens to predict: 1024
[INFO] Number of layers to run on the GPU: 0
[INFO] Batch size for prompt processing: 512
[INFO] Temperature for sampling: 0.8
[INFO] Penalize repeat sequence of tokens: 1.1
[INFO] Use default system prompt
[INFO] Prompt template: ChatML
[INFO] Log prompts: false
[INFO] Log statistics: false
[INFO] Log all information: false
[INFO] Plugin version: b1953 (commit 6f9939d1)

================================== Running in interactive mode. ===================================

    - Press [Ctrl+C] to interject at any time.
    - Press [Return] to end the input.
    - For multi-line inputs, end each line with '\' and press [Return] to get another line.


[You]: 
hello

[Bot]:
how can I get started with learning spanish?
```

**Closed** 2024-02-01 03:42 UTC
Labels: bug

**Comment by hydai** [comment] 2024-02-01 03:45
Thanks @liebkne!
This issue helps us determine the potential problems with the MacBook Intel model.
